Repository rohit-gohri/redocusaurus, pull requests merged in 2022-03, with the labels that each got.

#134 Add Forem to "Who uses Redocusaurus" list
  website/docs/who-is-using-redocusaurus.md
Labels: documentation

#139 Fix release scripts
  .changeset/cool-bobcats-collect.md
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/version.yml
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarn/releases/yarn-3.1.0.cjs
  .yarn/releases/yarn-3.2.0.cjs
  .yarnrc.yml
  package.json
  packages/docusaurus-theme-redoc/package.json
  yarn.lock
Labels: dependencies, builds

#140 Fix version script
  .changeset/tame-cheetahs-jog.md
  .github/workflows/version.yml
  package.json
  packages/docusaurus-theme-redoc/package.json
  yarn.lock
Labels: dependencies

#138 💥 Use build time parsing of schemas 💥
  .changeset/many-trees-hug.md
  .changeset/plenty-months-double.md
  .changeset/proud-lizards-itch.md
  .changeset/sixty-cougars-ring.md
  .vscode/settings.json
  package.json
  packages/docusaurus-plugin-redoc/Readme.md
  packages/docusaurus-plugin-redoc/package.json
  packages/docusaurus-plugin-redoc/src/index.ts
  packages/docusaurus-plugin-redoc/src/options.ts
  packages/docusaurus-plugin-redoc/src/types/common.d.ts
  packages/docusaurus-theme-redoc/Readme.md
  packages/docusaurus-theme-redoc/package.json
  packages/docusaurus-theme-redoc/src/hooks/useSpec.ts
  packages/docusaurus-theme-redoc/src/index.ts
  packages/docusaurus-theme-redoc/src/merge.ts
  packages/docusaurus-theme-redoc/src/redocData.ts
  packages/docusaurus-theme-redoc/src/theme/ApiDoc/ApiDoc.tsx
  packages/docusaurus-theme-redoc/src/theme/ApiSchema/ApiSchema.tsx
  packages/docusaurus-theme-redoc/src/theme/Redoc/Redoc.tsx
  packages/docusaurus-theme-redoc/src/theme/useSpecData.ts
  packages/docusaurus-theme-redoc/src/types/common.d.ts
  packages/docusaurus-theme-redoc/src/types/common.ts
  packages/docusaurus-theme-redoc/src/types/modules.d.ts
  packages/docusaurus-theme-redoc/src/types/options.d.ts
  packages/docusaurus-theme-redoc/src/types/util.d.ts
  packages/redocusaurus/src/index.ts
  website/docs/guides/schema-imports.mdx
  website/docs/guides/server-side-rendering.md
  website/docusaurus.config.js
  website/src/pages/examples/custom-layout/index.jsx
  website/src/pages/examples/custom-page/index.jsx
  website/src/theme/Root/index.tsx
  yarn.lock
Labels: enhancement

#103 Update docs
  .github/workflows/e2e.yml
  README.md
  packages/docusaurus-plugin-redoc/Readme.md
  packages/docusaurus-plugin-redoc/package.json
  packages/docusaurus-theme-redoc/Readme.md
  packages/docusaurus-theme-redoc/package.json
  packages/docusaurus-theme-redoc/src/theme/Redoc/Redoc.tsx
  packages/redocusaurus/Readme.md
  packages/redocusaurus/package.json
  website/docs/getting-started/Installation.md
  website/docs/getting-started/plugin-options.md
  website/docs/getting-started/theme-options.md
  website/docs/guides/build-time-rendering.md
  website/docs/guides/schema-imports.mdx
  website/snapshots.js
  website/src/pages/index.jsx
  website/vercel.json
Labels: documentation

#148 Add support for multiple yamls, uses openapi to bundle yamls
  .changeset/new-poems-return.md
  packages/docusaurus-plugin-redoc/package.json
  packages/docusaurus-plugin-redoc/src/index.ts
  packages/docusaurus-plugin-redoc/src/options.ts
  website/docusaurus.config.js
  website/examples/multi-yaml/index.yaml
  website/examples/multi-yaml/pets.yaml
  yarn.lock
Labels: enhancement

#149 Fix server build styles
  .changeset/purple-trainers-switch.md
  packages/docusaurus-theme-redoc/src/index.ts
  packages/docusaurus-theme-redoc/src/merge.ts
  packages/docusaurus-theme-redoc/src/redocData.ts
  packages/docusaurus-theme-redoc/src/theme/Redoc/Redoc.tsx
  packages/docusaurus-theme-redoc/src/theme/Redoc/ServerStyles.tsx
  packages/docusaurus-theme-redoc/src/theme/Redoc/Styles.tsx
  packages/docusaurus-theme-redoc/src/theme/ServerStyle/index.tsx
  packages/docusaurus-theme-redoc/src/types/modules.d.ts
  website/src/theme/Root/index.tsx
Labels: styles, builds

#152 Fix styling issues
  .changeset/fifty-rockets-perform.md
  packages/docusaurus-theme-redoc/src/theme/ApiSchema/ApiSchema.tsx
  packages/docusaurus-theme-redoc/src/theme/Redoc/Redoc.tsx
  packages/docusaurus-theme-redoc/src/theme/Redoc/ServerStyles.tsx
  packages/docusaurus-theme-redoc/src/theme/Redoc/Styles.tsx
  packages/docusaurus-theme-redoc/src/theme/Redoc/styles.css
  packages/docusaurus-theme-redoc/src/utils/useSpec.ts
Labels: styles

#145 v1.0.0 Beta
  .changeset/fifty-rockets-perform.md
  .changeset/lazy-grapes-rest.md
  .changeset/many-trees-hug.md
  .changeset/new-poems-return.md
  .changeset/orange-donkeys-marry.md
  .changeset/plenty-months-double.md
  .changeset/proud-lizards-itch.md
  .changeset/purple-trainers-switch.md
  .changeset/sixty-cougars-ring.md
  .vscode/settings.json
  package.json
  packages/docusaurus-plugin-redoc/Readme.md
  packages/docusaurus-plugin-redoc/package.json
  packages/docusaurus-plugin-redoc/src/index.ts
  packages/docusaurus-plugin-redoc/src/options.ts
  packages/docusaurus-plugin-redoc/src/types/common.d.ts
  packages/docusaurus-theme-redoc/Readme.md
  packages/docusaurus-theme-redoc/package.json
  packages/docusaurus-theme-redoc/src/index.ts
  packages/docusaurus-theme-redoc/src/redocData.ts
  packages/docusaurus-theme-redoc/src/theme/ApiDoc/ApiDoc.tsx
  packages/docusaurus-theme-redoc/src/theme/ApiSchema/ApiSchema.tsx
  packages/docusaurus-theme-redoc/src/theme/Redoc/Redoc.tsx
  packages/docusaurus-theme-redoc/src/theme/Redoc/ServerStyles.tsx
  packages/docusaurus-theme-redoc/src/theme/Redoc/Styles.tsx
  packages/docusaurus-theme-redoc/src/theme/Redoc/styles.css
  packages/docusaurus-theme-redoc/src/theme/ServerStyle/index.tsx
  packages/docusaurus-theme-redoc/src/theme/useSpecData.ts
  packages/docusaurus-theme-redoc/src/types/common.d.ts
  packages/docusaurus-theme-redoc/src/types/common.ts
  packages/docusaurus-theme-redoc/src/types/modules.d.ts
  packages/docusaurus-theme-redoc/src/types/options.d.ts
  packages/docusaurus-theme-redoc/src/types/util.d.ts
  packages/docusaurus-theme-redoc/src/utils/useSpec.ts
  packages/redocusaurus/src/index.ts
  website/docs/guides/build-time-rendering.md
  website/docs/guides/schema-imports.mdx
  website/docusaurus.config.js
  website/openapi/multi-yaml/components/pets.yaml
  website/openapi/multi-yaml/index.yaml
  website/src/pages/examples/custom-layout/index.jsx
  website/src/pages/examples/custom-page/index.jsx
  website/src/theme/Root/index.tsx
  yarn.lock
Labels: release

#153 Fix prism re-highlighting code
  .changeset/rotten-windows-enjoy.md
  packages/docusaurus-theme-redoc/src/global.ts
  packages/docusaurus-theme-redoc/src/index.ts
  packages/docusaurus-theme-redoc/src/redocData.ts
  packages/docusaurus-theme-redoc/src/theme/ApiSchema/ApiSchema.tsx
  packages/docusaurus-theme-redoc/src/theme/Redoc/Redoc.tsx
  packages/docusaurus-theme-redoc/src/theme/Redoc/ServerStyles.tsx
  packages/docusaurus-theme-redoc/src/theme/Redoc/Styles.tsx
  packages/docusaurus-theme-redoc/src/utils/useSpec.ts
Labels: styles

#144 Update docs for v1
  package.json
  packages/docusaurus-plugin-redoc/package.json
  packages/docusaurus-theme-redoc/Readme.md
  packages/docusaurus-theme-redoc/package.json
  packages/redocusaurus/Readme.md
  packages/redocusaurus/package.json
  packages/redocusaurus/src/index.ts
  website/docs/getting-started/Installation.md
  website/docs/getting-started/plugin-options.md
  website/docs/getting-started/theme-options.md
  website/docs/guides/build-time-rendering.md
  website/docs/guides/migrating-to-v1.md
  website/docs/guides/schema-imports.mdx
  website/docusaurus.config.js
  website/openapi/multi-file/components/pets.yaml
  website/openapi/multi-file/openapi.yaml
  website/openapi/single-file/openapi.yaml
  website/openapi/swagger/swagger.json
  website/package.json
  website/snapshots.js
  website/src/pages/examples/index.jsx
  website/static/openapi-component.yaml
  website/static/openapi-page.yaml
  yarn.lock
Labels: documentation

#158 Disable menu/scroll tracking in ApiSchema
  .changeset/orange-peaches-applaud.md
  packages/docusaurus-theme-redoc/src/theme/ApiSchema/ApiSchema.tsx
  packages/docusaurus-theme-redoc/src/utils/useSpec.ts
Labels: bug
