Repository rohit-gohri/redocusaurus, pull requests merged in 2022-05, with the labels that each got.

#168 fix: update source of isDarkTheme
  packages/docusaurus-theme-redoc/package.json
  packages/docusaurus-theme-redoc/src/utils/useSpec.ts
  yarn.lock
Labels: bug, dependencies, builds

#176 Upgrade to beta.20
  .changeset/gorgeous-flies-count.md
  .changeset/quiet-taxis-eat.md
  package.json
  packages/docusaurus-plugin-redoc/package.json
  packages/docusaurus-plugin-redoc/src/index.ts
  packages/docusaurus-plugin-redoc/src/options.ts
  packages/docusaurus-theme-redoc/package.json
  packages/docusaurus-theme-redoc/src/index.ts
  packages/docusaurus-theme-redoc/src/theme/useSpecData.ts
  packages/docusaurus-theme-redoc/src/utils/useSpec.ts
  packages/redocusaurus/package.json
  website/docs/getting-started/plugin-options.md
  website/package.json
  yarn.lock
Labels: dependencies, builds

#178 Fix: process is undefined error
  .changeset/tasty-lions-glow.md
  package.json
  packages/docusaurus-plugin-redoc/package.json
  packages/docusaurus-theme-redoc/package.json
  packages/docusaurus-theme-redoc/src/index.ts
  packages/docusaurus-theme-redoc/src/tty.ts
  packages/redocusaurus/Readme.md
  packages/redocusaurus/package.json
  website/package.json
  yarn.lock
Labels: bug, builds

#180 Add ApiDocMdx component for nested apis
  .changeset/thick-cheetahs-love.md
  packages/docusaurus-theme-redoc/src/theme/ApiDocMdx/ApiDocMdx.tsx
  packages/docusaurus-theme-redoc/src/theme/ApiDocMdx/index.ts
  packages/docusaurus-theme-redoc/src/theme/Redoc/Redoc.tsx
  packages/docusaurus-theme-redoc/src/types/common.d.ts
  packages/docusaurus-theme-redoc/src/types/modules.d.ts
  packages/docusaurus-theme-redoc/src/utils/useSpec.ts
  website/docs/guides/build-time-rendering.md
  website/docs/guides/migrating-to-v1.md
  website/docs/guides/multiple-apis.md
  website/docs/guides/schema-imports.mdx
  website/docs/nested/_category_.yaml
  website/docs/nested/nested-1.mdx
  website/docs/nested/nested-2.mdx
  website/snapshots.js
  yarn.lock
Labels: enhancement

#187 Always add scala to additional languages
  .changeset/healthy-phones-chew.md
  .yarn/releases/yarn-3.2.0.cjs
  .yarn/releases/yarn-3.2.1.cjs
  .yarnrc.yml
  package.json
  packages/docusaurus-theme-redoc/src/redocData.ts
  yarn.lock
Labels: bug

#189 Handle multiple instances of presets
  .changeset/perfect-cheetahs-visit.md
  .github/workflows/version.yml
  packages/docusaurus-plugin-redoc/src/index.ts
  packages/docusaurus-plugin-redoc/src/options.ts
  packages/docusaurus-theme-redoc/src/theme/ApiDocMdx/ApiDocMdx.tsx
  packages/docusaurus-theme-redoc/src/types/common.d.ts
  packages/docusaurus-theme-redoc/src/types/modules.d.ts
  packages/docusaurus-theme-redoc/src/utils/useSpec.ts
  packages/redocusaurus/src/index.ts
Labels: enhancement

#191 Update docs
  .changeset/four-tips-relate.md
  .github/workflows/e2e.yml
  packages/redocusaurus/Readme.md
  website/docs/getting-started/Installation.md
  website/docs/guides/schema-imports.mdx
  website/docusaurus.config.js
Labels: documentation
