Repository rohit-gohri/redocusaurus, pull requests merged in 2022-06, with the labels that each got.

#198 fix(theme): dark and light AppStore menu fix
  packages/docusaurus-theme-redoc/src/theme/ApiSchema/ApiSchema.tsx
  packages/docusaurus-theme-redoc/src/theme/Redoc/Redoc.tsx
  packages/docusaurus-theme-redoc/src/theme/Redoc/ServerStyles.tsx
  packages/docusaurus-theme-redoc/src/theme/Redoc/Styles.tsx
  packages/docusaurus-theme-redoc/src/utils/useSpec.ts
Labels: bug, integration

#204 Upgrade to beta-21
  .changeset/short-pans-wait.md
  packages/docusaurus-plugin-redoc/package.json
  packages/docusaurus-theme-redoc/package.json
  packages/redocusaurus/package.json
  website/package.json
  yarn.lock
Labels: dependencies

#206 Move to peer dependencies
  .changeset/honest-lamps-smell.md
  package.json
  packages/docusaurus-plugin-redoc/package.json
  packages/docusaurus-theme-redoc/package.json
  packages/redocusaurus/package.json
  website/package.json
  yarn.lock
Labels: dependencies

#210 Don't dispose store in SSR
  .changeset/spicy-eels-sleep.md
  packages/docusaurus-theme-redoc/src/utils/useSpec.ts
Labels: bug

#212 Add publish to test tag for each PR
  .github/workflows/build.yml
  .github/workflows/e2e.yml
  .github/workflows/version.yml
  scripts/version.sh
Labels: builds
